#!/bin/sh
#

export APP_USER=_www
export APP_GROUP=_www

export APP_ROOT=/srv/php7
export APP_DATA=/srv/www

#####################################################################

app_prepare() {

    [ -d $APP_ROOT/var/log ] || mkdir -p $APP_ROOT/var/log
    [ -d $APP_ROOT/var/tmp ] || mkdir -p $APP_ROOT/var/tmp
    [ -d $APP_ROOT/var/run ] || mkdir -p $APP_ROOT/var/run

    chown -R $APP_USER:$APP_USER $APP_ROOT/var/*

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
