#!/bin/sh
#

export APP_USER=daemon
export APP_GROUP=daemon

#####################################################################

app_prepare() {

    for dir in lib log run tmp; do
        [ -d ${wbapp}/var/${dir}/redis ] ||
            mkdir -p ${wbapp}/var/${dir}/redis
    done

    if [ ! -e ${wbapp}/etc/redis ]; then
        ln -s ../../webox/redis/etc ${wbapp}/etc/redis
    fi

    if [ ! -f ${wbapp}/etc/redis/conf.d/useful.conf ]; then
        touch ${wbapp}/etc/redis/conf.d/useful.conf
    fi

    chown -R $APP_USER:$APP_GROUP ${wbapp}/var/*/redis

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
