#!/bin/sh
#

export WBX_VERSION=10

if [ -z "$WBX_APPS" ]; then
    export WBX_APPS='nginx mysql redis php'
fi

if ! echo $PATH | grep -q ${wbapp}; then
    export PATH=${wbapp}/bin:${wbapp}/sbin:$PATH
fi

if ! echo $PATH | grep -q ${wbcom}; then
    export PATH=${wbcom}/bin:${wbcom}/sbin:$PATH
fi

if ! echo $LD_LIBRARY_PATH | grep -q ${wbcom}; then
    export LD_LIBRARY_PATH=${wbapp}/lib:${wbcom}/lib
fi

#####################################################################

if [ ! -x ${wbcom}/runtime ]; then
    chmod +x ${wbapp}/misc/*/*
    chmod +x ${wbcom}/runtime
    chmod +x ${wbcom}/wbx_*
fi
