#!/bin/sh
#

if [ -z "$WBX_VERSION" ]; then
    . ${wbcom}/runtime
fi

#####################################################################

wbx_own_perm() {

    local APP_UID=${2:-0}
    local APP_GID=${3:-0}

    if [ -z $1 ] || [ ${#1} -lt 3 ] ; then
        echo "can't apply perm to this dir $1"
        exit 1
    fi

    chown -R $APP_UID:$APP_GID $1

    find $1 \( ! -perm 0644 -type f \) -exec chmod 0644 {} \;
    find $1 \( ! -perm 0755 -type d \) -exec chmod 0755 {} \;

}

wbx_app_install() {

    local APP_NAME APP_EXDIR

    local APP_LIST="$@"
    if [ $# -eq 0 ]; then
        APP_LIST=`ls ${wbapp}/misc/`
    fi

    local ETC_TARGET=${wbapp}/etc
    if [ ! -d $ETC_TARGET ]; then
        mkdir -p $ETC_TARGET
    fi

    for APP_NAME in $APP_LIST; do

        APP_EXDIR=${wbapp}/misc/$APP_NAME

        if [ -d $APP_EXDIR/etc ]; then
            wbx_own_perm $APP_EXDIR/etc
            if [ ! -e $ETC_TARGET/$APP_NAME ]; then
                ln -s $APP_EXDIR/etc $ETC_TARGET/$APP_NAME
            fi
        fi

        if [ -x $APP_EXDIR/prepare ]; then
            echo "exec $APP_EXDIR/prepare"
            $APP_EXDIR/prepare prepare
        fi

    done

    echo $WBX_VERSION > $ETC_TARGET/version

}

#####################################################################

[ $# -gt 0 ] && wbx_app_install "$@"
