#!/bin/bash
#

homebrew_init() {

    if [ ! -x $whome/bin/brew ]; then
        git clone https://github.com/Homebrew/brew.git $whome
    fi

    sed -i~ "s#/Cellar#/cell#g" $whome/Library/Homebrew/brew.sh

}

taps_register() {

    local wbtap=`brew --repository anrip/webox`

    if [ ! -e $wbtap/Formula ]; then
        mkdir -p $wbtap &&
            ln -s $wbase/Formula $wbtap/Formula
    fi

    if [ ! -d `brew --repository homebrew/core` ]; then
        brew tap homebrew/core
    fi

}

brew_install() {

    if [ -f $wbase/Formula/$1.sh ]; then
        $wbase/Formula/$1.sh
        return $?
    fi

    if [ -f $wbase/Formula/$1.rb ]; then
        brew install -v anrip/webox/$1
        return $?
    fi

    brew install -v $1

}

brew_cleanup() {

    local vvv

    brew deps --tree "$@" \
        | sed "s/[│─├└─]//g;s/ //g" \
        | sed "s#^.\+/##g" \
        | sort -k2n | uniq \
        > deps-yes.txt

    rm -rf deps-no.txt
    for vvv in `ls webox/cell`; do
        if ! grep -q "^$vvv$" deps-yes.txt; then
            echo $vvv >>deps-no.txt
        fi
    done

    brew rm -f `cat < deps-no.txt`

    rm -rf deps-*.txt

    brew cleanup

}
