#!/bin/sh
#

export APP_USER=_mysql
export APP_GROUP=_mysql

export APP_ROOT=/srv/wbapp

#####################################################################

app_prepare() {

    [ -d $APP_ROOT/var/log/mysql ] || mkdir -p $APP_ROOT/var/log/mysql
    [ -d $APP_ROOT/var/run/mysql ] || mkdir -p $APP_ROOT/var/run/mysql
    [ -d $APP_ROOT/var/tmp/mysql ] || mkdir -p $APP_ROOT/var/tmp/mysql

    if [ ! -f $APP_ROOT/var/log/mysql/error.log ]; then
        touch $APP_ROOT/var/log/mysql/error.log
    fi

    if [ ! -f $APP_ROOT/var/lib/mysql/ibdata1 ]; then
        $APP_ROOT/bin/mysqld --initialize-insecure \
            --basedir=$APP_ROOT --datadir=$APP_ROOT/var/lib/mysql
    fi

    chown -R $APP_USER:$APP_USER $APP_ROOT/var/*/mysql

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
