#!/bin/sh
#

export APP_USER=_mysql
export APP_GROUP=_mysql

#####################################################################

app_prepare() {

    for dir in lib log run tmp; do
        [ -d ${wbapp}/var/${dir}/mysql ] ||
            mkdir -p ${wbapp}/var/${dir}/mysql
    done

    if [ ! -e ${wbapp}/etc/mysql ]; then
        ln -s ../../webox/mysql/etc ${wbapp}/etc/mysql
    fi

    if [ ! -f ${wbapp}/var/log/mysql/error.log ]; then
        touch ${wbapp}/var/log/mysql/error.log
    fi

    if [ ! -f ${wbapp}/var/lib/mysql/ibdata1 ]; then
        ${wbapp}/sbin/mysqld --initialize-insecure \
            --basedir=${wbapp} --datadir=${wbapp}/var/lib/mysql
    fi

    chown -R $APP_USER:$APP_GROUP ${wbapp}/var/*/mysql

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
