#!/bin/sh
#

####################################################################

cd ~

plat=$(uname -s)-$(uname -m)
name=Webox-${plat}-v6.0414.tgz

if [ $(which wget) ]; then
    wget -c -O ${name} http://get.anrip.com/webox/${name}
else
    curl -C - -o ${name} http://get.anrip.com/webox/${name}
fi

tar -xvf ${name}
rm -rf ${name}

chown -R 0:0  srv
chmod -R 0777 srv/webroot/*

####################################################################

[ -e /srv ] || mkdir -p /srv
cp -av srv/* /srv/

rm -rf srv/ ${name}

####################################################################

[ -x /srv/service ] && /srv/service start

if [ -x /usr/sbin/service ]; then
    /srv/webox/bin/wkit service_setup
fi
