#!/bin/sh
#

####################################################################

cd ~

if [ -x /usr/bin/macerror ]; then
    name=webox-osx-v5.0812.tgz
fi

if [ -x /usr/bin/apt-get ]; then
    name=webox-ubu-v5.0812.tgz
fi

if [ $(which wget) ]; then
    wget -c -O ${name} http://dev.anrip.com/webox/${name}
else
    curl -C - -o ${name} http://dev.anrip.com/webox/${name}
fi

tar -xvf ${name} && rm ${name}

chown -R 0:0  srv
chmod -R 0777 srv/webroot/*

####################################################################

[ -e /srv ] || mkdir -p /srv
cp -av srv/* /srv/
rm -rf srv/

####################################################################

[ -x /srv/service ] && /srv/service start

if [ -x /usr/bin/apt-get ]; then
    /srv/webox/bin/wkit service_setup
fi
