#!/bin/sh
#

####################################################################

cd ~

plat=$(uname -s)-$(getconf LONG_BIT)
name=Webox-${plat}bit-v5.0902.tgz

if [ $(which wget) ]; then
    wget -c -O ${name} http://dev.anrip.com/webox/${name}
else
    curl -C - -o ${name} http://dev.anrip.com/webox/${name}
fi

tar -xvf ${name}
rm -rf ${name}

chown -R 0:0  srv
chmod -R 0777 srv/webroot/*

rm -rf srv/webroot srv/*/var
rm -rf srv/*/etc

rm -rf srv/node

####################################################################

[ -x /srv/service ] && /srv/service stop

for x in php5 nginx mysql redis webox; do
    ls /srv/${x} | grep -v 'etc\|var' | xargs -I {} rm -rf /srv/${x}/{}
done

rm -rf /srv/common /srv/library /srv/update

cp -av srv/* /srv/
rm -rf srv/

####################################################################

[ -x /srv/service ] && /srv/service start

if [ -x /usr/sbin/service ]; then
    /srv/webox/bin/wkit service_setup
fi
