#!/bin/sh
#

export APP_NAME=redis

export APP_USER=daemon
export APP_GROUP=daemon

export APP_ROOT=/srv/redis

#####################################################################

app_prepare() {

    [ -d $APP_ROOT/var/log ] || mkdir -p $APP_ROOT/var/log
    [ -d $APP_ROOT/var/tmp ] || mkdir -p $APP_ROOT/var/tmp
    [ -d $APP_ROOT/var/run ] || mkdir -p $APP_ROOT/var/run

    chown -R $APP_USER:$APP_USER $APP_ROOT/var

    if [ ! -f $APP_ROOT/etc/conf.d/useful.conf ]; then
        touch $APP_ROOT/etc/conf.d/useful.conf
    fi

}
