#!/bin/sh
#

APP_USER=daemon
APP_GROUP=daemon

#####################################################################

app_dataset() {

    chown -R 0:0 ${whome}/etc/nginx

    for SDIR in log run tmp; do
        mkdir -p ${whome}/var/$SDIR/nginx
        app_userlet ${whome}/var/$SDIR/nginx
    done

    if [ ! -d ${whome}/var/tmp/nginx/proxy_cache ]; then
        mkdir -p ${whome}/var/tmp/nginx/proxy_cache
        app_userlet ${whome}/var/tmp/nginx/proxy_cache
    fi

}

app_userlet() {

    chown -R $APP_USER:$APP_GROUP $1

    find $1 \( ! -perm 0644 -type f \) -exec chmod 0644 {} \;
    find $1 \( ! -perm 0755 -type d \) -exec chmod 0755 {} \;

}

#####################################################################

if [ "$1" = "auto" ]; then
    app_dataset
fi
