#!/bin/sh
#

export APP_USER=www-data
export APP_GROUP=www-data

export APP_ROOT=/srv/wbapp
export APP_DATA=/srv/htdoc

#####################################################################

app_prepare() {

    if ! grep $APP_GROUP /etc/group >/dev/null; then
        groupadd $APP_GROUP -g 33
    fi

    if ! grep $APP_USER /etc/passwd >/dev/null; then
        useradd $APP_USER -u 33 -g 33
        usermod $APP_USER -d $APP_DATA -s /usr/sbin/nologin
    fi

    [ -d $APP_ROOT/var/log/php5 ] || mkdir -p $APP_ROOT/var/log/php5
    [ -d $APP_ROOT/var/run/php5 ] || mkdir -p $APP_ROOT/var/run/php5
    [ -d $APP_ROOT/var/tmp/php5 ] || mkdir -p $APP_ROOT/var/tmp/php5

    chown -R $APP_USER:$APP_USER $APP_ROOT/var/*/php5

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
