#!/bin/sh
#

export APP_USER=_www
export APP_GROUP=_www

export APP_ROOT=/srv/nginx
export APP_DATA=/srv/www

#####################################################################

app_prepare() {

    if ! grep $APP_GROUP /etc/group >/dev/null; then
        groupadd $APP_GROUP -g 70
    fi

    if ! grep $APP_USER /etc/passwd >/dev/null; then
        useradd $APP_USER -u 70 -g 70
        usermod $APP_USER -d $APP_DATA -s /usr/bin/false
    fi

    [ -d $APP_ROOT/var/log ] || mkdir -p $APP_ROOT/var/log
    [ -d $APP_ROOT/var/tmp ] || mkdir -p $APP_ROOT/var/tmp
    [ -d $APP_ROOT/var/run ] || mkdir -p $APP_ROOT/var/run

    if [ ! -d $APP_ROOT/var/tmp/proxy_cache ]; then
        mkdir -p $APP_ROOT/var/tmp/proxy_cache
    fi

    chown -R $APP_USER:$APP_USER $APP_ROOT/var

}
