#!/bin/sh
#

. ${webox}/share/wkit/function

#####################################################################

APP_NAME=mysql

APP_BIN_FILE=${webox}/bin/mysqld_safe
APP_PID_FILE=${webox}/var/run/mysql/mysqld.pid

app_start() {

    $APP_BIN_FILE >/dev/null &

}

app_prepare() {

    app_varfix

    if [ ! -f ${webox}/var/log/mysql/error.log ]; then
        touch ${webox}/var/log/mysql/error.log
        app_userlet ${webox}/var/log/mysql
    fi

    if [ ! -d ${webox}/var/lib/mysql/mysql ]; then
        mysqld --initialize-insecure --user=$APP_USER
    fi

}

#####################################################################

app_do $1
