#!/bin/sh
#

. ${webox}/share/wkit/applet

#####################################################################

APP_NAME=nginx

APP_BIN_FILE=${webox}/sbin/nginx
APP_PID_FILE=${webox}/var/run/nginx/nginx.pid

app_stop() {

    $APP_BIN_FILE -s stop

}

app_reload() {

    $APP_BIN_FILE -s reload

}

app_prepare() {

    local vvv
    local pz=${webox}/etc/nginx/section/proxy_zone

    for vvv in `awk '$1=="proxy_cache_path" {print $2}' $pz*`; do
        mkdir -p $vvv
    done

    app_varfix log run tmp

}

#####################################################################

app_do $1
