#!/bin/sh
#

. ${webox}/share/wkit/function

#####################################################################

APP_NAME=redis

APP_BIN_FILE=${webox}/bin/redis-server
APP_PID_FILE=${webox}/var/run/redis/redis.pid

app_start() {

    $APP_BIN_FILE ${webox}/etc/redis/redis.conf

}

#####################################################################

app_do $1
