#!/bin/sh
#

export APP_USER=www-data
export APP_GROUP=www-data
export APP_DATA=${htdoc}

#####################################################################

app_prepare() {

    if ! grep $APP_GROUP /etc/group >/dev/null; then
        groupadd $APP_GROUP -g 33
    fi

    if ! grep $APP_USER /etc/passwd >/dev/null; then
        useradd $APP_USER -u 33 -g 33
        usermod $APP_USER -d $APP_DATA -s /usr/sbin/nologin
    fi

    [ -d ${wbapp}/var/log/php7 ] || mkdir -p ${wbapp}/var/log/php7
    [ -d ${wbapp}/var/run/php7 ] || mkdir -p ${wbapp}/var/run/php7
    [ -d ${wbapp}/var/tmp/php7 ] || mkdir -p ${wbapp}/var/tmp/php7

    chown -R $APP_USER:$APP_USER ${wbapp}/var/*/php7

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
