#!/bin/sh
#

export APP_USER=www-data
export APP_GROUP=www-data

#####################################################################

app_prepare() {

    if ! grep $APP_GROUP /etc/group >/dev/null; then
        groupadd $APP_GROUP -g 33
    fi

    if ! grep $APP_USER /etc/passwd >/dev/null; then
        useradd $APP_USER -u 33 -g 33
        usermod $APP_USER -d ${htdoc} -s /usr/sbin/nologin
    fi

    for dir in log run tmp; do
        [ -d ${wbapp}/var/${dir}/php7 ] ||
            mkdir -p ${wbapp}/var/${dir}/php7
    done

    if [ ! -e ${wbapp}/etc/php7 ]; then
        ln -s ../../webox/php7/etc ${wbapp}/etc/php7
    fi

    chown -R $APP_USER:$APP_GROUP ${wbapp}/var/*/php7

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
