#!/bin/sh
#

export APP_USER=mysql
export APP_GROUP=mysql

export APP_ROOT=/srv/wbapp

#####################################################################

app_prepare() {

    if ! grep $APP_GROUP /etc/group >/dev/null; then
        groupadd $APP_GROUP -g 77
    fi

    if ! grep $APP_USER /etc/passwd >/dev/null; then
        useradd $APP_USER -u 77 -g 77
        usermod $APP_USER -d $APP_ROOT -s /usr/sbin/nologin
    fi

    [ -d $APP_ROOT/var/lib/mysql ] || mkdir -p $APP_ROOT/var/lib/mysql
    [ -d $APP_ROOT/var/log/mysql ] || mkdir -p $APP_ROOT/var/log/mysql
    [ -d $APP_ROOT/var/run/mysql ] || mkdir -p $APP_ROOT/var/run/mysql
    [ -d $APP_ROOT/var/tmp/mysql ] || mkdir -p $APP_ROOT/var/tmp/mysql

    if [ ! -f $APP_ROOT/var/log/mysql/error.log ]; then
        touch $APP_ROOT/var/log/mysql/error.log
    fi

    if [ ! -f $APP_ROOT/var/lib/mysql/ibdata1 ]; then
        $APP_ROOT/sbin/mysqld --initialize-insecure \
            --basedir=$APP_ROOT --datadir=$APP_ROOT/var/lib/mysql
    fi

    chown -R $APP_USER:$APP_USER $APP_ROOT/var/*/mysql

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
