#!/bin/sh
#

export APP_USER=mysql
export APP_GROUP=mysql

#####################################################################

app_prepare() {

    if ! grep -q $APP_GROUP /etc/group; then
        groupadd $APP_GROUP -g 77
    fi

    if ! grep -q $APP_USER /etc/passwd; then
        useradd $APP_USER -u 77 -g 77
        usermod $APP_USER -d ${wbapp} -s /usr/sbin/nologin
    fi

    for dir in lib log run tmp; do
        [ -d ${wbapp}/var/${dir}/mysql ] ||
            mkdir -p ${wbapp}/var/${dir}/mysql
    done

    if [ ! -f ${wbapp}/var/log/mysql/error.log ]; then
        touch ${wbapp}/var/log/mysql/error.log
    fi

    chown -R $APP_USER:$APP_GROUP ${wbapp}/var/*/mysql

    if [ ! -f ${wbapp}/var/lib/mysql/ibdata1 ]; then
        ${wbapp}/sbin/mysqld --initialize-insecure \
            --basedir=${wbapp} --datadir=${wbapp}/var/lib/mysql
    fi

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
