#!/bin/sh
#

export WBX_VERSION=12

if [ -z "$WBX_APPS" ]; then
    export WBX_APPS='nginx mysql redis php'
fi

if ! echo $PATH | grep -q ${whome}; then
    export PATH=${whome}/bin:${whome}/sbin:$PATH
fi

#####################################################################

wbx_error() {
    echo "[ERROR] $@"
    exit 1
}

wbx_install() {

    local APP_LIST="$@"

    if [ $# -eq 0 ]; then
        APP_LIST=`ls ${wbapp}/`
    fi

    local APP_NAME APP_INIT

    for APP_NAME in $APP_LIST; do
        APP_INIT=${wbapp}/$APP_NAME/prepare
        [ -x $APP_INIT ] && $APP_INIT prepare
    done

}

wbx_service() {

    if [ $# -eq 0 ]; then
        wbx_error "bad service args"
    fi

    if [ ! -x ${wbapp}/$1/service ]; then
        wbx_error "not found service: $1"
    fi

    ${wbapp}/$1/service $2

}
