#!/bin/sh
#

export APP_USER=www-data
export APP_GROUP=www-data

#####################################################################

app_prepare() {

    if ! grep -q $APP_GROUP /etc/group; then
        groupadd $APP_GROUP -g 33
    fi

    if ! grep -q $APP_USER /etc/passwd; then
        useradd $APP_USER -u 33 -g 33
        usermod $APP_USER -d ${htdoc} -s /usr/sbin/nologin
    fi

    for dir in log run tmp; do
        [ -d ${wbapp}/var/${dir}/php5 ] ||
            mkdir -p ${wbapp}/var/${dir}/php5
    done

    chown -R $APP_USER:$APP_GROUP ${wbapp}/var/*/php5

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
