#!/bin/bash
#

if [ -f $(pwd)/wb_base ]; then
    source $(pwd)/wb_base
fi

if [ -z ${wbdir} ]; then
    echo "Please use './package' to run this script"
    exit 1
fi

source ${wbdir}/wb_function

#####################################################################MIN#

if [ "${1}" == "-min" ]; then

    find /srv -type f -name "*.a" -exec rm {} \;
    find /srv -type f -name "*.la" -exec rm {} \;

    wb_strip /srv/mysql/bin
    wb_strip /srv/nginx/sbin
    wb_strip /srv/php5/bin
    wb_strip /srv/php5/sbin
    wb_strip /srv/redis/bin
    wb_strip /srv/webox/bin

fi


#####################################################################PKG#

rm -rf /srv/*/var/run/*
rm -rf /srv/*/var/log/*
rm -rf /srv/*/var/tmp/*

rm -rf /srv/mysql/var/data/*.*

rm -rf /srv/webox/var/ready/*

find /srv -type f -name "*.log" -exec rm {} \;
find /srv -type f -name "*.pid" -exec rm {} \;
find /srv -type f -name ".DS_Store" -exec rm {} \;
find /srv -type f -name "sess_*" -exec rm {} \;
find /srv -type d -name "lost+found" -exec rm {} \;

tar -czvf ${wbdir}/webox${1}.tgz /srv
