#!/bin/bash
#

if_exit() {

    [ $1 -eq 0 ] || exit $1

}

copy_parents() {

    [ -d $1 ] && cp -av --parents $@

}

rm_empty_dir() {

    local vv

    while true; do
        vv=`find $1 -type d -empty`
        if [ -z "$vv" ]; then
            break
        fi
        rm -rvf $vv
    done

}

rm_invalid_ln() {

    local vv

    for vv in `find $target -follow -type l`; do
        [ -e $vv ] || rm -vf $vv
    done

}
