#!/bin/bash
#

homebrew_init() {

    export HOMEBREW_NO_AUTO_UPDATE="1"

    if [ ! -x $webox/bin/brew ]; then
        git clone https://github.com/Homebrew/brew.git $webox
    fi

    if grep -q "/Cellar" $webox/Library/Homebrew/brew.sh; then
        sed -i~ "s#/Cellar#/cell#g" $webox/Library/Homebrew/brew.sh
    fi

    # 注册软件仓库

    if [ ! -d `brew --repository homebrew/core` ]; then
        brew tap homebrew/core
    fi

    local mytap=`brew --repository anrip/webox`

    if [ ! -e $mytap/Formula ]; then
        mkdir -p $mytap && ln -s $wbase/Formula $mytap
    fi

}

cell_install() {

    if [ -f $wbase/Formula/$1.sh ]; then
        source $wbase/Formula/$1.sh
        cell_install_$1
        if_exit $?
        return
    fi

    if [ -f $wbase/Formula/$1.rb ]; then
        brew install -v anrip/webox/$1
    else
        brew install -v $1
    fi

    if [ ! -d $webox/cell/$1 ]; then
        echo "Failed to install $1"
        exit 1
    fi

}

cell_cleanup() {

    local vvv

    rm -f deps-*.txt

    brew deps --tree "$@" \
        | sed "s#[│─├└─]##g;s# ##g" \
        | sed "s#^.\+/##g" \
        | sort -k2n | uniq \
        > deps-yes.txt

    for vvv in `ls $webox/cell/`; do
        if ! grep -q "^$vvv$" deps-yes.txt; then
            echo $vvv >>deps-no.txt
        fi
    done

    if [ -e deps-no.txt ]; then
        brew rm -f `cat deps-no.txt`
    fi

    rm -f deps-*.txt

    brew cleanup

}
