#!/bin/bash
#

make_profile() {

    local vv vvv
    local target=${1:-mini}

    mkdir -p $target

    # 复制配置文件

    cp -rf $wbase/Declare/basefs/* $target/
    ln -sf cell/wkit/service $target/

    chmod -R +x $target/cell/wkit

    # 替换预置变量

    for vvv in `grep '${\w\+}' -rl $target/etc`; do
        make_profile_sed $vvv
    done

    for vvv in `grep '${\w\+}' -rl $target/cell/wkit`; do
        make_profile_sed $vvv
    done

}

make_profile_sed() {

    local htdoc=$webox/var/www

    sed -i~ \
        -e "s#\${webox}#$webox#g" \
        -e "s#\${htdoc}#$htdoc#g" \
        $1

    rm -f $1~

}
