#!/bin/sh
#

export APP_USER=_www
export APP_GROUP=_www

#####################################################################

app_prepare() {

    local DIR

    for DIR in log run tmp; do
        [ -d ${wbapp}/var/$DIR/nginx ] ||
            mkdir -p ${wbapp}/var/$DIR/nginx
    done

    if [ ! -d ${wbapp}/var/tmp/nginx/proxy_cache ]; then
        mkdir -p ${wbapp}/var/tmp/nginx/proxy_cache
    fi

    chown -R $APP_USER:$APP_GROUP ${wbapp}/var/*/nginx

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
