#!/bin/bash
#

if [ -f $(pwd)/wb_base ]; then
    source $(pwd)/wb_base
fi

if [ -z ${wbdir} ]; then
    echo "Please use './complie' to run this script"
    exit 1
fi

source ${wbdir}/wb_function

#################################################################Library#

for pkg in $(ls ${wbdir}/wb_library); do
    source ${wbdir}/wb_library/${pkg}
done

wb_inst_m4
wb_inst_autoconf
wb_inst_automake
wb_inst_bison
wb_inst_pcre
wb_inst_zlib
wb_inst_openssl
wb_inst_jpeg
wb_inst_libpng
wb_inst_freetype
wb_inst_ncurses
wb_inst_libiconv
wb_inst_libmcrypt
wb_inst_libxml2
wb_inst_gettext
wb_inst_curl
wb_inst_cmake

wb_rtm ${webox}

#################################################################Package#

for pkg in $(ls ${wbdir}/wb_package); do
    source ${wbdir}/wb_package/${pkg}
done

wb_inst_php5
wb_inst_nginx
wb_inst_mysql
wb_inst_redis

#################################################################Profile#

cp -av ${wbdir}/wb_profile/* /srv/

chown -R 0:0  /srv
chmod -R 0755 /srv/service
chmod -R 0755 /srv/webox/bin/wkit
chmod -R 0755 /srv/webox/wkit
chmod -R 0755 /srv/webroot/*

find /srv/*/etc ! \( -uid 0 -gid 0 \) -exec chown 0:0 {} \;
find /srv/*/etc \( ! -perm 0644 -type f \) -exec chmod 0644 {} \;
find /srv/*/etc \( ! -perm 0755 -type d \) -exec chmod 0755 {} \;
