#!/bin/bash
#

if [ -f $(pwd)/wb_base ]; then
    source $(pwd)/wb_base
fi

if [ -z ${wbdir} ]; then
    echo "Please use './wk_publish' to run this script"
    exit 1
fi

source ${wbdir}/wb_function

#####################################################################MIN#

if [ "${1}" == "-min" ]; then

    mkdir -p /srv/webox/{bin2,etc2}
    mv /srv/webox/bin/{wkit,curl,openssl} /srv/webox/bin2/
    mv /srv/webox/etc/{mysql,nginx,php5,redis} /srv/webox/etc2/

    rm -rf /srv/webox/lib/{cmake,gettext,libmcrypt,terminfo,preloadable_*}
    rm -rf /srv/webox/{bin,etc,man,share}

    find /srv -name "*.a" -exec rm {} \;
    find /srv -name "*.la" -exec rm {} \;

    mv /srv/webox/bin2 /srv/webox/bin
    mv /srv/webox/etc2 /srv/webox/etc

    wb_strip /srv/webox/bin

    wb_strip /srv/mysql/bin
    wb_strip /srv/redis/bin

    wb_strip /srv/nginx/sbin

fi

#####################################################################CLS#

rm -rf /srv/*/var/run/*
rm -rf /srv/*/var/log/*
rm -rf /srv/*/var/tmp/*

rm -rf /srv/webox/var/ready/*

rm -rf /srv/mysql/var/data/*.cnf

xattr -rd com.apple.quarantine /srv

find /srv -type f -name "*.log" -exec rm {} \;
find /srv -type f -name "*.pid" -exec rm {} \;
find /srv -type f -name ".DS_Store" -exec rm {} \;
find /srv -type f -name "sess_*" -exec rm {} \;
find /srv -type d -name "lost+found" -exec rm {} \;

#####################################################################PKG#

plat=$(uname -s)-$(getconf LONG_BIT)
dist=${wbdir}/Weobx-${plat}bit${1}.tgz

tar --exclude webox2 -czvf ${dist} /srv

