#!/bin/bash
#

if [ -f $(pwd)/wb_base ]; then
    source $(pwd)/wb_base
fi

if [ -z ${wbdir} ]; then
    echo "Please use './package' to run this script"
    exit 1
fi

source ${wbdir}/wb_function

#####################################################################MIN#

if [ "${1}" == "-min" ]; then

    for d in cmake gettext libmcrypt terminfo preloadable_*; do
        rm -rf /srv/webox/lib/${d}
    done

    mkdir -p /srv/webox/bin2
    for f in wkit curl openssl; do
        mv /srv/webox/bin/${f} /srv/webox/bin2/
    done

    rm -rf /srv/webox/{bin,etc,man,share}
    mv /srv/webox/bin2 /srv/webox/bin

    find /srv -name "*.a" -exec rm {} \;
    find /srv -name "*.la" -exec rm {} \;

    wb_strip /srv/webox/bin

    wb_strip /srv/mysql/bin
    wb_strip /srv/redis/bin

    wb_strip /srv/nginx/sbin


fi

#####################################################################CLS#

rm -rf /srv/*/var/run/*
rm -rf /srv/*/var/log/*
rm -rf /srv/*/var/tmp/*

rm -rf /srv/mysql/var/data/*.*

rm -rf /srv/webox/var/ready/*

find /srv -type f -name "*.log" -exec rm {} \;
find /srv -type f -name "*.pid" -exec rm {} \;
find /srv -type f -name ".DS_Store" -exec rm {} \;
find /srv -type f -name "sess_*" -exec rm {} \;
find /srv -type d -name "lost+found" -exec rm {} \;

#####################################################################PKG#

plat=$(uname -s)-$(getconf LONG_BIT)
dist=${wbdir}/Weobx-${plat}bit${1}.tgz

tar --exclude webox2 -czvf ${dist} /srv

