#!/bin/sh
#

export APP_USER=_www
export APP_GROUP=_www

#####################################################################

app_prepare() {

    local DIR

    for DIR in log run tmp; do
        [ -d ${wbapp}/var/$DIR/php5 ] ||
            mkdir -p ${wbapp}/var/$DIR/php5
    done

    chown -R $APP_USER:$APP_GROUP ${wbapp}/var/*/php5

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
