#!/bin/sh
#

export APP_USER=www-data
export APP_GROUP=www-data

#####################################################################

app_useradd() {

    if ! grep -q $APP_GROUP /etc/group; then
        groupadd $APP_GROUP -g 33
    fi

    if ! grep -q $APP_USER /etc/passwd; then
        useradd $APP_USER -u 33 -g 33
        usermod $APP_USER -d ${htdoc} -s /usr/sbin/nologin
    fi

}

app_userlet() {

    chown -R $APP_USER:$APP_GROUP $1

    find $1 \( ! -perm 0644 -type f \) -exec chmod 0644 {} \;
    find $1 \( ! -perm 0755 -type d \) -exec chmod 0755 {} \;

}

app_dataset() {

    local DIR

    for DIR in log run tmp; do
        mkdir -p ${whome}/var/$DIR/php
        app_userlet ${whome}/var/$DIR/php
    done

    if [ ! -e ${whome}/etc/php ]; then
        ln -s ${wbapp}/php/etc ${whome}/etc/php
    fi

    app_userlet ${whome}/etc/php

}

#####################################################################

if [ "$1" = "prepare" ]; then
    app_useradd
    app_dataset
fi

