#!/bin/sh
#

export APP_NAME=redis

export APP_USER=daemon
export APP_GROUP=daemon

#####################################################################

app_prepare() {

    [ -d ${wbapp}/var/lib/redis ] || mkdir -p ${wbapp}/var/lib/redis
    [ -d ${wbapp}/var/log/redis ] || mkdir -p ${wbapp}/var/log/redis
    [ -d ${wbapp}/var/run/redis ] || mkdir -p ${wbapp}/var/run/redis
    [ -d ${wbapp}/var/tmp/redis ] || mkdir -p ${wbapp}/var/tmp/redis

    chown -R $APP_USER:$APP_USER ${wbapp}/var/*/redis

    if [ ! -f ${wbapp}/etc/redis/conf.d/useful.conf ]; then
        touch ${wbapp}/etc/redis/conf.d/useful.conf
    fi

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
