#!/bin/sh
#

export APP_USER=www-data
export APP_GROUP=www-data

export APP_ROOT=/srv/php7
export APP_DATA=/srv/www

#####################################################################

app_prepare() {

    if ! grep $APP_GROUP /etc/group >/dev/null; then
        groupadd $APP_GROUP -g 33
    fi

    if ! grep $APP_USER /etc/passwd >/dev/null; then
        useradd $APP_USER -u 33 -g 33
        usermod $APP_USER -d $APP_DATA -s /usr/sbin/nologin
    fi

    [ -d $APP_ROOT/var/log ] || mkdir -p $APP_ROOT/var/log
    [ -d $APP_ROOT/var/tmp ] || mkdir -p $APP_ROOT/var/tmp
    [ -d $APP_ROOT/var/run ] || mkdir -p $APP_ROOT/var/run

    chown -R $APP_USER:$APP_USER $APP_ROOT/var

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
