#!/bin/bash
#

source /srv/webox/runtime

if [ $# -eq 1 ]; then
    wkit service php5  "${@}"
    wkit service php7  "${@}"
    wkit service redis "${@}"
    wkit service mysql "${@}"
    wkit service nginx "${@}"
else
    wkit service "${@}"
fi
