#!/bin/sh
#

export APP_USER=_www
export APP_GROUP=_www

export APP_BIN_FILE=${wbapp}/sbin/php-fpm5
export APP_PID_FILE=${wbapp}/var/run/php5/fpm.pid

#####################################################################

app_start() {

    if app_check ; then
        echo "php5 is already running"
        exit 1
    fi

    echo "start php5 ..."

    local POOL_CONF POOL_ROOT

    for POOL_CONF in ${wbapp}/etc/php5/pool.d/*.conf; do

        POOL_CONF=${POOL_CONF##*/}
        POOL_ROOT=${htdoc}/${POOL_CONF%.*}

        mkdir -p $POOL_ROOT/web
        mkdir -p $POOL_ROOT/log
        mkdir -p $POOL_ROOT/temp/session

        chown -R $APP_USER:$APP_GROUP $POOL_ROOT

    done

    $APP_BIN_FILE

}

app_stop() {

    if ! app_check ; then
        echo "php5 is not running"
        exit 1
    fi

    echo "stop php5 ..."

    kill -TERM `cat $APP_PID_FILE`

}

app_reload() {

    if ! app_check ; then
        echo "php5 is not running"
        exit 1
    fi

    echo "reload php5 ..."

    kill -USR2 `cat $APP_PID_FILE`

}

app_restart() {

    app_stop && sleep 3 && app_start

}

app_status() {

    app_check
    app_result 'status:' 'running' 'stopped'

}

app_check() {

    if [ ! -f $APP_PID_FILE ] ; then
        return 1
    fi

    if ! kill -0 `cat $APP_PID_FILE` 2>/dev/null ; then
        rm -f $APP_PID_FILE
        return 1
    fi

}

app_usage() {

    local DOES="start|stop|reload|restart|status"

    if ! echo "|$DOES|" | grep -q "|$1|"; then
        echo "Usage: wkit php5 {$DOES}"
        exit 1
    fi

}

app_result() {

    local CODE=$?
    local RIGHT=${2:-done}
    local ERROR=${3:-failed}

    if [ $CODE -eq 0 ]; then
        echo "$1 php5 \033[32m$RIGHT \033[0m"
    else
        echo "$1 php5 \033[31m$ERROR \033[0m"
    fi

    exit $CODE

}

#####################################################################

app_usage $1 || exit 1

app_$1
app_result $1
