#!/bin/bash
#

homebrew_init() {

    if [ ! -x $whome/bin/brew ]; then
        git clone https://github.com/Homebrew/brew.git $whome
    fi

    sed -i~ "s#/Cellar#/cell#g" $whome/Library/Homebrew/brew.sh

    if [ ! -d `brew --repository homebrew/core` ]; then
        brew tap homebrew/core
    fi

    local mytap=`brew --repository anrip/webox`

    if [ ! -e $mytap/Formula ]; then
        mkdir -p $mytap && ln -s $wbase/Formula $mytap
    fi

}

brew_install() {

    if [ -f $wbase/Formula/$1.sh ]; then
        source $wbase/Formula/$1.sh
        brew_install_$1
        if_exit $?
        return
    fi

    if [ -f $wbase/Formula/$1.rb ]; then
        brew install -v anrip/webox/$1
    else
        brew install -v $1
    fi

    if [ ! -d $whome/$1 ]; then
        exit 1
    fi

}

brew_cleanup() {

    local vvv

    rm -rf deps-*.txt

    brew deps --tree "$@" \
        | sed "s/[│─├└─]//g;s/ //g" \
        | sed "s#^.\+/##g" \
        | sort -k2n | uniq \
        > deps-yes.txt

    for vvv in `ls webox/cell`; do
        if ! grep -q "^$vvv$" deps-yes.txt; then
            echo $vvv >>deps-no.txt
        fi
    done

    if [ -e deps-no.txt ]; then
        brew rm -f `cat deps-no.txt`
    fi

    rm -rf deps-*.txt

    brew cleanup

}
