#!/bin/bash
#

make_profile() {

    local vv vvv
    local target=${1:-srv}

    # 复制配置文件

    cp -r -f $wbase/Declare/$osvar/* $target/
    chmod +x $target/app/*/* $target/app/perform

    # 替换预置变量

    grep '${htdoc}' -rl $target/app | while read -r vvv; do
        sed -i~ "s#\${htdoc}#$wbase/htdoc#g" $vvv
    done

    grep '${wbapp}' -rl $target/app | while read -r vvv; do
        sed -i~ "s#\${wbapp}#$wbase/app#g" $vvv
    done

    grep '${whome}' -rl $target/app | while read -r vvv; do
        sed -i~ "s#\${whome}#$whome#g" $vvv
    done

    # 清理临时文件

    find $target/app -name "*~" -type f -delete

}
