#!/bin/bash
#

make_profile() {

    local vv vvv
    local target=${1:-srv}

    mkdir -p $target

    # 复制配置文件

    cp -rf $wbase/Declare/basefs/* $target/
    ln -sf webox/share/wkit/service $target/service

    chmod -R +x $target/webox/share/wkit

    # 替换预置变量

    for vvv in `grep '${\w\+}' -rl $target/webox/etc`; do
        make_profile_sed $vvv
    done

    for vvv in `grep '${\w\+}' -rl $target/webox/share/wkit`; do
        make_profile_sed $vvv
    done

}

make_profile_sed() {

    local htdoc=$wbase/htdoc
    local whome=$wbase/webox

    sed -i~ \
        -e "s#\${htdoc}#$htdoc#g" \
        -e "s#\${whome}#$whome#g" \
        $1

    find $1 -name "*~" -type f -delete

}
