#!/bin/sh
#

export APP_USER=www-data
export APP_GROUP=www-data
export APP_DATA=${htdoc}

#####################################################################

app_prepare() {

    if ! grep $APP_GROUP /etc/group >/dev/null; then
        groupadd $APP_GROUP -g 33
    fi

    if ! grep $APP_USER /etc/passwd >/dev/null; then
        useradd $APP_USER -u 33 -g 33
        usermod $APP_USER -d $APP_DATA -s /usr/sbin/nologin
    fi

    [ -d ${wbapp}/var/log/nginx ] || mkdir -p ${wbapp}/var/log/nginx
    [ -d ${wbapp}/var/run/nginx ] || mkdir -p ${wbapp}/var/run/nginx
    [ -d ${wbapp}/var/tmp/nginx ] || mkdir -p ${wbapp}/var/tmp/nginx

    if [ ! -d ${wbapp}/var/tmp/nginx/proxy_cache ]; then
        mkdir -p ${wbapp}/var/tmp/nginx/proxy_cache
    fi

    chown -R $APP_USER:$APP_USER ${wbapp}/var/*/nginx

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
