#!/bin/sh
#

export APP_USER=www-data
export APP_GROUP=www-data

#####################################################################

app_prepare() {

    if ! grep $APP_GROUP /etc/group >/dev/null; then
        groupadd $APP_GROUP -g 33
    fi

    if ! grep $APP_USER /etc/passwd >/dev/null; then
        useradd $APP_USER -u 33 -g 33
        usermod $APP_USER -d ${htdoc} -s /usr/sbin/nologin
    fi

    for dir in log run tmp; do
        [ -d ${wbapp}/var/${dir}/nginx ] ||
            mkdir -p ${wbapp}/var/${dir}/nginx
    done

    if [ ! -e ${wbapp}/etc/nginx ]; then
        ln -s ../../webox/nginx/etc ${wbapp}/etc/nginx
    fi

    if [ ! -d ${wbapp}/var/tmp/nginx/proxy_cache ]; then
        mkdir -p ${wbapp}/var/tmp/nginx/proxy_cache
    fi

    chown -R $APP_USER:$APP_GROUP ${wbapp}/var/*/nginx

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
