#!/bin/sh
#

if [ -z "$WBX_VERSION" ]; then
    . ${wbcom}/runtime
fi

#####################################################################

wbx_app_service() {

    local APP_NAME=$1
    local APP_ACTION=$2

    local APP_SCRIPT=${wbapp}/misc/$1/service

    if [ ! -x $APP_SCRIPT ]; then
        echo "can't exec $APP_SCRIPT"
        exit 1
    fi

    $APP_SCRIPT $APP_ACTION

}

#####################################################################

[ $# -gt 0 ] && wbx_app_service "$@"
