#!/bin/sh
#

export APP_USER=_www
export APP_GROUP=_www
export APP_DATA=${htdoc}

#####################################################################

app_prepare() {

    [ -d ${wbapp}/var/log/php7 ] || mkdir -p ${wbapp}/var/log/php7
    [ -d ${wbapp}/var/run/php7 ] || mkdir -p ${wbapp}/var/run/php7
    [ -d ${wbapp}/var/tmp/php7 ] || mkdir -p ${wbapp}/var/tmp/php7

    chown -R $APP_USER:$APP_USER ${wbapp}/var/*/php7

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
