#!/bin/sh
#

export APP_USER=_www
export APP_GROUP=_www

#####################################################################

app_prepare() {

    for dir in log run tmp; do
        [ -d ${wbapp}/var/${dir}/php7 ] ||
            mkdir -p ${wbapp}/var/${dir}/php7
    done

    if [ ! -e ${wbapp}/etc/php7 ]; then
        if [ -f /.dockerenv ]; then
            cp -a ${webox}/php7/etc ${wbapp}/etc/php7
        else
            ln -s ${webox}/php7/etc ${wbapp}/etc/php7
        fi
    fi

    chown -R $APP_USER:$APP_GROUP ${wbapp}/var/*/php7

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
