#!/bin/sh
#

export WBX_VERSION=10

export PATH=${webox}/bin:$PATH

export PATH=${wblib}/bin:$PATH

export PATH=${wbapp}/bin:$PATH
export PATH=${wbapp}/sbin:$PATH

export LD_LIBRARY_PATH=${wblib}/lib:${wbapp}/lib

#####################################################################

wbx_app_run() {

    local WBX_APP=$1
    local WBX_ACTION=$2
    local WBX_SCRIPT=${webox}/$1

    case $WBX_ACTION in
        prepare)
            WBX_SCRIPT=$WBX_SCRIPT/prepare
        ;;
        *)
            WBX_SCRIPT=$WBX_SCRIPT/service
        ;;
    esac

    if [ ! -x $WBX_SCRIPT ]; then
        echo "can't exec $WBX_SCRIPT"
        exit 1
    fi

    $WBX_SCRIPT $WBX_ACTION

}

wbx_own_perm() {

    local WBX_UID=${2:-0}
    local WBX_GID=${3:-0}

    if [ -z $1 ] || [ ${#1} -lt 3 ] ; then
        echo "can't apply perm to this dir $1"
        exit 1
    fi

    find $1 \( ! -perm 0644 -type f \) -exec chmod 0644 {} \;
    find $1 \( ! -perm 0755 -type d \) -exec chmod 0755 {} \;
    find $1 ! \( -uid $WBX_UID -gid $WBX_GID \) -exec chown $WBX_UID:$WBX_GID {} \;

}

wbx_fix_install() {

    local WBX_APP WBX_APP_EXTRA

    chmod +x ${webox}/*/prepare
    chmod +x ${webox}/*/service

    if [ ! -d ${wbapp}/etc ]; then
        mkdir -p ${wbapp}/etc
    fi

    for WBX_APP_EXTRA in ${webox}/*; do

        WBX_APP=${WBX_APP_EXTRA##*/}

        if [ ! -x $WBX_APP_EXTRA/prepare ]; then
            continue
        fi

        if [ ! -e ${wbapp}/etc/$WBX_APP ]; then
            if [ -f /.dockerenv ]; then
                cp -a ${webox}/$WBX_APP/etc ${wbapp}/etc/$WBX_APP
            else
                ln -s ${webox}/$WBX_APP/etc ${wbapp}/etc/$WBX_APP
            fi
        fi

        wbx_own_perm ${wbapp}/etc/$WBX_APP
        wbx_own_perm ${wbapp}/etc/$WBX_APP
        wbx_own_perm ${wbapp}/etc/$WBX_APP

        echo "exec $WBX_APP_EXTRA/prepare"
        $WBX_APP_EXTRA/prepare prepare

    done

}
