#!/bin/sh
#

export PATH=/srv/wbcom/bin:${PATH}

export PATH=/srv/wbapp/bin:${PATH}
export PATH=/srv/wbapp/sbin:${PATH}

export LD_LIBRARY_PATH=/srv/wbcom/lib:/srv/wbapp/lib

#####################################################################

wbx_app_run() {

    local WBX_APP=$1
    local WBX_ACTION=$2
    local WBX_SCRIPT=/srv/webox/$1

    case $WBX_ACTION in
        prepare)
            WBX_SCRIPT=$WBX_SCRIPT/prepare
        ;;
        *)
            WBX_SCRIPT=$WBX_SCRIPT/service
        ;;
    esac

    [ -x $WBX_SCRIPT ] || chmod +x $WBX_SCRIPT
    $WBX_SCRIPT $WBX_ACTION

}

wbx_all_install() {

    local WBX_APP WBX_APP_PATH

    if [ ! -d /srv/wbapp/etc ]; then
        mkdir -p /srv/wbapp/etc
    fi

    for WBX_APP_PATH in /srv/webox/*; do

        WBX_APP=${WBX_APP_PATH##*/}

        if [ -d $WBX_APP_PATH/etc ]; then

            echo "install wbapp $WBX_APP"

            if [ ! -e /srv/wbapp/etc/$WBX_APP ]; then
                ln -s ../../webox/$WBX_APP/etc /srv/wbapp/etc/$WBX_APP
            fi

            wbx_app_run $WBX_APP prepare

        fi

    done

    find /srv/wbapp/etc ! \( -uid 0 -gid 0 \) -exec chown 0:0 {} \;
    find /srv/wbapp/etc \( ! -perm 0644 -type f \) -exec chmod 0644 {} \;
    find /srv/wbapp/etc \( ! -perm 0755 -type d \) -exec chmod 0755 {} \;

}
