#!/bin/sh
#

export APP_NAME=nginx

export APP_BIN_FILE=${wbapp}/sbin/nginx
export APP_PID_FILE=${wbapp}/var/run/nginx/nginx.pid

#####################################################################

app_start() {

    if app_check ; then
        echo "$APP_NAME is already running"
        exit 1
    fi

    echo "start $APP_NAME ..."

    $APP_BIN_FILE -c ${wbapp}/etc/nginx/nginx.conf

}

app_stop() {

    if ! app_check ; then
        echo "$APP_NAME is not running"
        exit 1
    fi

    echo "stop $APP_NAME ..."

    $APP_BIN_FILE -s stop

}

app_reload() {

    if ! app_check ; then
        echo "$APP_NAME is not running"
        exit 1
    fi

    echo "reload $APP_NAME ..."

    $APP_BIN_FILE -s reload

}

app_restart() {

    app_stop && sleep 3 && app_start

}

app_status() {

    app_check
    app_result 'status:' 'running' 'stopped'

}

app_check() {

    if [ ! -f $APP_PID_FILE ] ; then
        return 1
    fi

    if ! kill -0 `cat $APP_PID_FILE` 2>/dev/null ; then
        rm -f $APP_PID_FILE
        return 1
    fi

}

app_usage() {

    local DOES="start|stop|reload|restart|status"

    if ! echo "|$DOES|" | grep -q "|$1|"; then
        echo "Usage: wkit $APP_NAME {$DOES}"
        exit 1
    fi

}

app_result() {

    local CODE=$?
    local RIGHT=${2:-done}
    local ERROR=${3:-failed}

    if [ $CODE -eq 0 ]; then
        echo "$1 $APP_NAME \033[32m$RIGHT \033[0m"
    else
        echo "$1 $APP_NAME \033[31m$ERROR \033[0m"
    fi

    exit $CODE

}

#####################################################################

app_usage $1 || exit 1

app_$1
app_result $1
