#!/bin/sh
#

if [ -n $WBX_VERSION ]; then
    . ${webox}/runtime
fi

mkdir -p /var/lib/webox

if [ ! -f /var/lib/webox/version ]; then
    echo 0 > /var/lib/webox/version
fi

if [ `cat /var/lib/webox/version` -lt $WBX_VERSION ]; then
    echo $WBX_VERSION > /var/lib/webox/version
    wbx_fix_install
fi
