#!/bin/sh
#

export PATH=${webox}/bin:${PATH}

export PATH=${wblib}/bin:${PATH}

export PATH=${wbapp}/bin:${PATH}
export PATH=${wbapp}/sbin:${PATH}

export LD_LIBRARY_PATH=${wblib}/lib:${wbapp}/lib

#####################################################################

wbx_app_run() {

    local WBX_APP=$1
    local WBX_ACTION=$2
    local WBX_SCRIPT=${webox}/$1

    case $WBX_ACTION in
        prepare)
            WBX_SCRIPT=$WBX_SCRIPT/prepare
        ;;
        *)
            WBX_SCRIPT=$WBX_SCRIPT/service
        ;;
    esac

    [ -x $WBX_SCRIPT ] || chmod +x $WBX_SCRIPT
    $WBX_SCRIPT $WBX_ACTION

}

wbx_all_prepare() {

    if [ ! -d ${wbapp}/etc ]; then
        mkdir -p ${wbapp}/etc
    fi

    for WBX_SCRIPT in ${webox}/*/prepare; do
        [ -x $WBX_SCRIPT ] || chmod +x $WBX_SCRIPT
        echo "run $WBX_SCRIPT"
        $WBX_SCRIPT prepare
    done

    find ${webox}/*/etc ! \( -uid 0 -gid 0 \) -exec chown 0:0 {} \;
    find ${webox}/*/etc \( ! -perm 0644 -type f \) -exec chmod 0644 {} \;
    find ${webox}/*/etc \( ! -perm 0755 -type d \) -exec chmod 0755 {} \;

}
