#!/bin/sh
#

export PATH=/srv/bin:${PATH}

export PATH=${wbcom}/bin:${PATH}

export PATH=${wbapp}/bin:${PATH}
export PATH=${wbapp}/sbin:${PATH}

export LD_LIBRARY_PATH=${wbcom}/lib:${wbapp}/lib

#####################################################################

wbx_app_run() {

    local WBX_APP=$1
    local WBX_ACTION=$2
    local WBX_SCRIPT=${webox}/$1

    case $WBX_ACTION in
        prepare)
            WBX_SCRIPT=$WBX_SCRIPT/prepare
        ;;
        *)
            WBX_SCRIPT=$WBX_SCRIPT/service
        ;;
    esac

    [ -x $WBX_SCRIPT ] || chmod +x $WBX_SCRIPT
    $WBX_SCRIPT $WBX_ACTION

}

wbx_all_install() {

    local WBX_APP WBX_APP_PATH

    if [ ! -d ${wbapp}/etc ]; then
        mkdir -p ${wbapp}/etc
    fi

    for WBX_APP_PATH in ${webox}/*; do

        WBX_APP=${WBX_APP_PATH##*/}

        if [ -d $WBX_APP_PATH/etc ]; then

            echo "install wbapp $WBX_APP"

            if [ ! -e ${wbapp}/etc/$WBX_APP ]; then
                ln -s ../../webox/$WBX_APP/etc ${wbapp}/etc/$WBX_APP
            fi

            wbx_app_run $WBX_APP prepare

        fi

    done

    find ${wbapp}/etc ! \( -uid 0 -gid 0 \) -exec chown 0:0 {} \;
    find ${wbapp}/etc \( ! -perm 0644 -type f \) -exec chmod 0644 {} \;
    find ${wbapp}/etc \( ! -perm 0755 -type d \) -exec chmod 0755 {} \;

}
