#!/bin/sh
#

cd ~

name=Webox-$(uname -s)-$(uname -m).tgz

if type wget >/dev/null 2>&1; then
    wget -c -O ${name} http://get.vmlu.com/webox/${name}
else
    curl -C - -o ${name} http://get.vmlu.com/webox/${name}
fi

echo "Extracting from ${name}"
tar -xf ${name} && rm ${name}

if [ ! -d ~/srv/webox ]; then
    echo "Can't download ${name}"
    exit 1
fi
