#!/bin/sh
#

webox=/opt/webox

if [ -e $webox ]; then
    echo "$webox already exists"
    exit 1
fi

####################################################################

cd ~

if [ `uname` = "Darwin" ]; then
    name=webox-macos-v10.tgz
else
    name=webox-linux-v12.tgz
fi

if type wget >/dev/null; then
    wget -c -O $name http://get.vmlu.com/webox/$name
else
    curl -C - -o $name http://get.vmlu.com/webox/$name
fi

echo "Decompressing $name"

tar -xf $name && rm $name

if [ $? -ne 0 ]; then
    echo "Can't download $name"
    exit 1
fi

####################################################################

echo "Installing to $webox"

cp -af ~/webox $webox
rm -rf ~/webox

if [ $? -ne 0 ]; then
    echo "Can't install to $webox"
    exit 1
fi

####################################################################

$webox/service start
