#!/bin/sh
#

cd ~

name=Webox-$(uname -s)-$(uname -m).tgz

if type wget >/dev/null 2>&1; then
    wget -c -O ${name} http://get.vmlu.com/webox/${name}
else
    curl -C - -o ${name} http://get.vmlu.com/webox/${name}
fi

echo "Installing with ${name}"
tar -xf ${name} && rm ${name}

if [ ! -d ~/srv/webox ]; then
    echo "Can't download ${name}"
    exit 1
fi

####################################################################

[ -e /srv ] || mkdir -p /srv

cp -av ~/srv/* /srv/
rm -rf ~/srv/

####################################################################

[ -x /srv/service ] && /srv/service start
