#!/bin/sh
#

cd ~

if [ `uname` = "Darwin" ]; then
    name=webox-macos-v10.tgz
else
    name=webox-linux-v11.tgz
fi

if type wget >/dev/null; then
    wget -c -O ${name} http://get.vmlu.com/webox/${name}
else
    curl -C - -o ${name} http://get.vmlu.com/webox/${name}
fi

echo "Installing with ${name}"
tar -xf ${name} && rm ${name}

if [ ! -d ~/srv/webox ]; then
    echo "Can't download ${name}"
    exit 1
fi

####################################################################

[ -e /srv ] || mkdir -p /srv

cp -av ~/srv/* /srv/
rm -rf ~/srv/

####################################################################

[ -x /srv/service ] && /srv/service start
