#!/bin/sh
#

webox=/opt/webox

if [ ! -e $webox ]; then
    echo "$webox haven't installed"
    exit 1
fi

####################################################################

cd ~

if [ `uname` = "Darwin" ]; then
    name=webox-macos-v10.tgz
else
    name=webox-linux-v13.tgz
fi

if type wget >/dev/null; then
    wget -c -O $name http://get.vmlu.com/webox/$name
else
    curl -C - -o $name http://get.vmlu.com/webox/$name
fi

echo "Decompressing $name"

tar -xf $name && rm $name

if [ $? -ne 0 ]; then
    echo "Can't download $name"
    exit 1
fi

####################################################################

echo "Updating $webox"

$webox/service stop

cp -au ~/webox/* $webox/
rm -rf ~/webox

####################################################################

$webox/service start
