#!/bin/sh
#

cd ~

if type curl >/dev/null 2>&1; then
    curl http://get.vmlu.com/webox/wb-fetch | sh
else
    wget -qO- http://get.vmlu.com/webox/wb-fetch | sh
fi

if [ ! -d ~/srv/webox ]; then
    echo "can't download webox.tgz"
    exit 1
fi

####################################################################

[ -x /srv/service ] && /srv/service stop

rm -rf /var/lib/webox

rm -rf srv/webox/*/etc
cp -av srv/* /srv/

rm -rf srv/

####################################################################

[ -x /srv/service ] && /srv/service start
