#!/bin/sh
#

cd ~

if [ `uname` = "Darwin" ]; then
    name=webox-macos-v10.tgz
else
    name=webox-linux-v12.tgz
fi

if type wget >/dev/null; then
    wget -c -O $name http://get.vmlu.com/webox/$name
else
    curl -C - -o $name http://get.vmlu.com/webox/$name
fi

echo "Updating with $name"
tar -xf $name && rm $name

if [ $? -ne 0 ]; then
    echo "Can't download $name"
    exit 1
fi

####################################################################

[ -x /srv/service ] && /srv/service stop

cp -au ~/srv/* /srv/
rm -rf ~/srv/

####################################################################

[ -x /srv/service ] && /srv/service start
