#!/bin/sh
#

APP_USER=daemon
APP_GROUP=daemon

APP_BIN_FILE=${webox}/sbin/php-fpm
APP_PID_FILE=${webox}/var/run/php/fpm.pid

#####################################################################

app_start() {

    if app_check ; then
        echo "php is already running"
        exit 1
    fi

    echo "start php ..."

    for POOL in `ls ${webox}/etc/php/pool.d/*.conf`; do

        POOL=${POOL%.*}
        POOL=${POOL##*/}

        mkdir -p ${htdoc}/${POOL}
        mkdir -p ${webox}/var/log/php/${POOL}
        mkdir -p ${webox}/var/tmp/php/${POOL}/upload
        mkdir -p ${webox}/var/tmp/php/${POOL}/session

        chown -R $APP_USER:$APP_GROUP ${htdoc}/${POOL}
        chown -R $APP_USER:$APP_GROUP ${webox}/var/*/php/${POOL}

    done

    $APP_BIN_FILE -p ${webox}

}

app_stop() {

    if ! app_check ; then
        echo "php is not running"
        exit 1
    fi

    echo "stop php ..."

    kill -TERM `cat $APP_PID_FILE`

}

app_reload() {

    if ! app_check ; then
        echo "php is not running"
        exit 1
    fi

    echo "reload php ..."

    kill -USR2 `cat $APP_PID_FILE`

}

app_restart() {

    app_stop && sleep 3 && app_start

}

app_status() {

    app_check
    app_result 'status:' 'running' 'stopped'

}

app_check() {

    if [ ! -f $APP_PID_FILE ] ; then
        return 1
    fi

    if ! kill -0 `cat $APP_PID_FILE` 2>/dev/null ; then
        rm -f $APP_PID_FILE
        return 1
    fi

}

app_usage() {

    DOES="start|stop|reload|restart|status"

    if ! echo "|$DOES|" | grep -q "|$1|"; then
        echo "Usage: wkit php {$DOES}"
        exit 1
    fi

}

app_result() {

    CODE=$?

    RIGHT=${2:-done}
    ERROR=${3:-failed}

    if [ $CODE -eq 0 ]; then
        echo "$1 php $RIGHT"
    else
        echo "$1 php $ERROR"
    fi

    exit $CODE

}

#####################################################################

app_usage $1 || exit 1

app_$1
app_result $1
