#!/bin/sh
#

export APP_USER=daemon
export APP_GROUP=daemon

#####################################################################

app_userlet() {

    chown -R $APP_USER:$APP_GROUP $1

    find $1 \( ! -perm 0644 -type f \) -exec chmod 0644 {} \;
    find $1 \( ! -perm 0755 -type d \) -exec chmod 0755 {} \;

}

app_dataset() {

    local DIR

    for DIR in log run tmp; do
        mkdir -p ${whome}/var/$DIR/php
        app_userlet ${whome}/var/$DIR/php
    done

    if [ ! -e ${whome}/etc/php ]; then
        ln -s ${wbapp}/php/etc ${whome}/etc/php
    fi

    chown -R 0:0 ${whome}/etc/php

}

#####################################################################

if [ "$1" = "once" ]; then
    app_dataset
fi
