#!/bin/sh
#

export APP_USER=daemon
export APP_GROUP=daemon

#####################################################################

app_prepare() {

    local DIR

    for DIR in lib log run tmp; do
        [ -d ${wbapp}/var/$DIR/redis ] ||
            mkdir -p ${wbapp}/var/$DIR/redis
    done

    if [ ! -f ${wbapp}/etc/redis/conf.d/useful.conf ]; then
        touch ${wbapp}/etc/redis/conf.d/useful.conf
    fi

    chown -R $APP_USER:$APP_GROUP ${wbapp}/var/*/redis

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
