#!/bin/bash
#

source Declare/runtime

env_initialize

##############################################BUILD##################

brew_install preload

brew_install nginx

brew_install node

brew_install php
brew_install php-ext

brew_install mysql
brew_install redis
