#!/bin/bash
#

source Declare/runtime.sh

env_initialize

##############################################MINIFY#################

mini=$wbase/srv-dist

make_profile $mini
make_package $mini/webox

ln -s app/perform $mini/service
