#!/bin/bash
#

source `pwd`/Declare/runtime

env_initialize

##############################################MINIFY#################

mini=$wbase/srv-dist

brew_cleanup gcc@7 glibc mysql nginx node php php-ext redis

make_package $mini/webox "mysql nginx node php redis"

make_profile $mini

ln -s app/srvkit $mini/service
