#!/bin/bash
#

source ./Declare/runtime

load_modules

mini=$wbase/srv-mini

##############################################MINIFY#################

cell_cleanup gcc@7 glibc mysql nginx node php php-ext redis

make_package $mini "mysql nginx node php redis"

make_profile $mini
