#!/bin/bash
#

if [ $UID -ne 0 ]; then
    echo "This script requires root privileges"
    exit 1
fi

##################################################WEBOX-BUILD-KIT-VAR#

export wkdir=$(pwd)

export wksrc=${wkdir}/source
export wkget=${wkdir}/storage
export wketc=${wkdir}/profile/$(uname)

if [ ! -f ${wketc}.rtm ]; then
    echo "$(uname) platform is not supported"
    exit 1
fi

[ -d ${wksrc} ] || mkdir -p ${wksrc}
[ -d ${wkget} ] || mkdir -p ${wkget}

find ${wkget} -name "*" -type f -size 0c | xargs -n 1 rm -f

#####################################################WEBOX-TARGET-VAR#

export htdoc=/srv/htdoc

export wbapp=/srv/app
export wbcom=/srv/webox

[ -d ${wbapp} ] || mkdir -p ${wbapp}
[ -d ${wbcom} ] || mkdir -p ${wbcom}

##############################################################RUNTIME#

export PATH=${wbapp}/bin:${wbcom}/bin:$PATH

export CPATH=${wbapp}/include:${wbcom}/include
export LIBRARY_PATH=${wbapp}/lib:${wbcom}/lib
export LD_LIBRARY_PATH=$LIBRARY_PATH

export PKG_CONFIG_PATH=${wbapp}/lib/pkgconfig:${wbcom}/lib/pkgconfig

mkdir -p ${wbapp}/include ${wbcom}/include
mkdir -p ${wbapp}/lib ${wbcom}/lib
