#!/bin/bash
#

if [ "$UID" != "0" ]; then
    echo "This script requires root privileges"
    exit 1
fi

#################################################################VAR#

[ -z ${wbdir} ] && wbdir=$(pwd)

[ -z ${webox} ] && webox=/srv/webox
[ -d ${webox} ] || mkdir -p ${webox}

[ -z ${wbget} ] && wbget=${wbdir}/storage
[ -d ${wbget} ] || mkdir -p ${wbget}

[ -z ${wbsrc} ] && wbsrc=${wbdir}/source
[ -d ${wbsrc} ] || mkdir -p ${wbsrc}

find ${wbget} -name "*" -type f -size 0c | xargs -n 1 rm -f

#################################################################RTM#

export PATH=${webox}/bin:${PATH}

export CPATH=${webox}/include
export LIBRARY_PATH=${webox}/lib
export LD_LIBRARY_PATH=${webox}/lib

mkdir -p ${CPATH} ${LIBRARY_PATH}

case $(uname) in
    "Linux")
        wbetc=${wbdir}/profile/Debian
    ;;
    "Darwin")
        wbetc=${wbdir}/profile/MacOS
    ;;
    *)
        exit 100
esac

source ${wbetc}.rtm
