#!/bin/bash
#

if [ "$UID" != "0" ]; then
    echo "This script requires root privileges"
    exit 1
fi

#####################################################WEBOX-TARGET-VAR#

export wbapp=/srv/wbapp
export wbcom=/srv/wbcom

[ -d ${wbapp} ] || mkdir -p ${wbapp}
[ -d ${wbcom} ] || mkdir -p ${wbcom}

##################################################WEBOX-BUILD-KIT-VAR#

export wkdir=$(pwd)

export wksrc=${wkdir}/source
export wkget=${wkdir}/storage

[ -d ${wksrc} ] || mkdir -p ${wksrc}
[ -d ${wkget} ] || mkdir -p ${wkget}

find ${wkget} -name "*" -type f -size 0c | xargs -n 1 rm -f

##############################################################RUNTIME#

export PATH=${wbapp}/bin:${wbcom}/bin:${PATH}

export CPATH=${wbapp}/include:${wbcom}/include
export LIBRARY_PATH=${wbapp}/lib:${wbcom}/lib
export LD_LIBRARY_PATH=$LIBRARY_PATH

mkdir -p ${wbapp}/include ${wbcom}/include
mkdir -p ${wbapp}/lib ${wbcom}/lib

case $(uname) in
    "Linux")
        wketc=${wkdir}/profile/Debian
    ;;
    "Darwin")
        wketc=${wkdir}/profile/MacOS
    ;;
    *)
        exit 10
esac

source ${wketc}.rtm
