#!/bin/bash
#

source Declare/runtime

mini=$wbase/srv-mini

##############################################MINIFY#################

mv $mini srv

rm -rf srv/etc/version
rm -rf srv/var/lib/*/*
rm -rf srv/var/log/*/*
rm -rf srv/var/run/*/*
rm -rf srv/var/tmp/*/*

tar czvf webox-linux-v12.tgz srv

mv srv $mini
