#!/bin/bash
#

source ./Declare/runtime

load_modules

##############################################MINIFY#################

mini=$webox-mini

[ -d $mini ] && mv $mini $mini-old


cell_cleanup "gcc@7 glibc nginx node php php-ext redis mysql"

make_package $mini "nginx node php redis mysql"
make_profile $mini
