#!/bin/bash
#

wk__error() {

    echo "Failed: $@"; exit 1

}

wk__error_check() {

    [ $? -ne 0 ] && wk__error $@

}

########################################################################

wk__fetch() {

    local save=${wkget}/${1##*/}

    [ -z $2 ] || save=${wkget}/$2
    [ -d ${save%/*} ] || mkdir -p ${save%/*}

    if [ $(which wget) ]; then
        wget --no-check-certificate -c -O ${save} $1
    else
        curl -k -L -C - -o ${save} $1
    fi

    echo ${save}

}

wk__apply() {

    local name=$2$3
    local dist=${wksrc}/$2

    [ -z $4 ] || name=$4$3
    [ -z $4 ] || dist=${wksrc}/$4

    if [ ! -d ${dist} ]; then

        echo "Appling: $1$2$3"

        local save=$(wk__fetch $1$2$3 ${name})

        [ -d ${dist%/*} ] || mkdir -p ${dist%/*}

        tar -xvf ${save} -C ${dist%/*}
        [ $? -ne 0 ] && rm -rf ${dist}

    fi

    cd ${dist}
    wk__error_check wk__apply ${dist}

    if [ -f Makefile ]; then make clean; fi

}

wk__strip() {

    local lst=${wksrc}/wk__strip_list

    rm -f ${lst}

    echo "Search $1 to strip ..."
    find $1 -type f | xargs file | grep 'Mach-O \|ELF \| ar z' >>${lst}

    sed -i~ 's/:.*//' ${lst}

    for line in $(<${lst}); do
        echo "Strip: ${line}"
        strip ${line}
    done

    rm -f ${lst}

}

wk__realpath() {

    sed -i~ "s#\${htdoc}#${htdoc}#g" `grep '${htdoc}' -rl $1`
    sed -i~ "s#\${wbapp}#${wbapp}#g" `grep '${wbapp}' -rl $1`
    sed -i~ "s#\${wblib}#${wblib}#g" `grep '${wblib}' -rl $1`
    sed -i~ "s#\${webox}#${webox}#g" `grep '${webox}' -rl $1`

    find $1 -name "*~" -type f -delete

}
