#!/bin/bash
#

source ./Declare/runtime

##############################################TARBALL################

mini=$wbase/webox-mini

rm -rf $mini/etc/version
rm -rf $mini/var/lib/*/*
rm -rf $mini/var/log/*/*
rm -rf $mini/var/run/*/*
rm -rf $mini/var/tmp/*/*


mv $mini webox
tar -czvf webox-linux-v12.tgz webox
mv webox $mini
