#!/bin/bash
#

source ./Declare/runtime

##############################################TARBALL################

mini=$webox-mini

rm -rf $mini/etc/version
rm -rf $mini/var/lib/mysql/aria_log*
rm -rf $mini/var/lib/mysql/ib*
rm -rf $mini/var/log/*/*
rm -rf $mini/var/run/*/*
rm -rf $mini/var/tmp/*/*

mv $mini webox
tar -czvf webox-linux-v13.tgz webox
mv webox $mini
