#!/bin/bash
#

source ./Declare/runtime

##############################################TARBALL################

mini=$wbase/srv-mini

rm -rf $mini/etc/version
rm -rf $mini/var/lib/*/*
rm -rf $mini/var/log/*/*
rm -rf $mini/var/run/*/*
rm -rf $mini/var/tmp/*/*


mv $mini srv
tar czvf webox-linux-v12.tgz srv
mv srv $mini
