#!/bin/bash
#

if [ -f $(pwd)/config ]; then
    source $(pwd)/config
fi

if [ -z ${wkdir} ]; then
    echo "Please use './wk_complie' to run this script"
    exit 1
fi

source ${wkdir}/function

#################################################################Package#

for pkg in ${wkdir}/library/*; do
    source ${pkg}
done

for pkg in ${wkdir}/app/*; do
    source ${pkg}
done

wk_inst_deps

wk_inst_mysql
wk_inst_redis

wk_inst_nginx

wk_inst_php5
wk_inst_php7

#################################################################Profile#

rm -rf ${wbcom}/share/{doc,info,man}
rm -rf ${wbapp}/share/{doc,info,man}
rm -rf ${wbapp}/share/{php5,php7}

cp -av ${wketc}/* /srv/
wk__realpath ${webox}

chown -R 0:0  /srv
chmod -R 0755 /srv/*/bin
chmod -R 0755 /srv/*/sbin
chmod -R 0755 /srv/service

source ${webox}/runtime
wbx_all_install
