#!/bin/bash
#

if [ -f $(pwd)/config ]; then
    source $(pwd)/config
fi

if [ -z ${wkdir} ]; then
    echo "Please use './wk_publish' to run this script"
    exit 1
fi

source ${wkdir}/function

#####################################################################MIN#

if [ "${1}" == "-min" ]; then

    mkdir -p ${wbcom}/bin2
    mv ${wbcom}/bin/{wkit,curl,openssl} ${wbcom}/bin2

    for d in cmake gettext libmcrypt terminfo preloadable_*; do
        rm -rf ${wbcom}/lib/${d}
    done

    rm -rf ${wbcom}/{bin,etc,man,share}
    mv ${wbcom}/bin2 ${wbcom}/bin

    find /srv -name "*.a" -exec rm {} \;
    find /srv -name "*.la" -exec rm {} \;

    wk__strip ${wbcom}/bin
    wk__strip ${wbapp}/bin

fi

#####################################################################CLS#

rm -rf ${wbapp}/var/log/*
rm -rf ${wbapp}/var/run/*
rm -rf ${wbapp}/var/tmp/*

rm -rf ${wbapp}/var/lib/mysql/*.cnf

if [ "$OS_TYPE" == "MacOS" ]; then
    xattr -rd com.apple.quarantine /srv
fi

find /srv -type f -name "*.log" -exec rm {} \;
find /srv -type f -name "*.pid" -exec rm {} \;
find /srv -type f -name ".DS_Store" -exec rm {} \;
find /srv -type f -name "sess_*" -exec rm {} \;
find /srv -type d -name "lost+found" -exec rm {} \;

#####################################################################PKG#

plat=$(uname -s)-$(getconf LONG_BIT)
dist=${wkdir}/Webox-${plat}bit${1}.tgz

tar --exclude builder -czvf ${dist} /srv
