#!/bin/bash
#

if [ -f $(pwd)/config ]; then
    source $(pwd)/config
fi

if [ -f ${wkdir}/function ]; then
    source ${wkdir}/function
else
    echo "Please use './wk_complie' to run this script"
    exit 1
fi

#################################################################Package#

for pkg in ${wkdir}/library/*; do
    source ${pkg}
done

for pkg in ${wkdir}/app/*; do
    source ${pkg}
done

wk_inst_deps

wk_inst_mysql
wk_inst_redis

wk_inst_nginx

wk_inst_php7
wk_inst_php5

#################################################################Profile#

cp -av ${wketc}/* /srv/
wk__realpath ${webox}

chown -R 0:0  /srv
chmod -R 0755 /srv/*/bin
chmod -R 0755 /srv/*/sbin
chmod -R 0755 /srv/service
