#!/bin/bash
#

if [ ! -f $(pwd)/config ]; then
    echo "Please use './run-build' to run me"
    exit 1
fi

source $(pwd)/config

source ${wketc}.rtm
source ${wkdir}/function

#################################################################Package#

for pkg in ${wkdir}/library/*; do
    source ${pkg}
done

for pkg in ${wkdir}/app/*; do
    source ${pkg}
done

wk_inst_libs

wk_inst_mysql
wk_inst_redis

wk_inst_nginx

wk_inst_php7

#################################################################Profile#

mkdir -p /tmp/wketc
cp -av ${wketc}/* /tmp/wketc

wk__realpath /tmp/wketc
cp -av /tmp/wketc/* /srv/

rm -r /tmp/wketc

chown -R 0:0  /srv
chmod -R 0755 /srv/*/bin
chmod -R 0755 /srv/*/sbin

ln -s ${wbcom}/bin/wkit /srv/service
