#!/bin/bash
#

if [ ! -f $(pwd)/config ]; then
    echo "Please use './run-publish' to run me"
    exit 1
fi

source $(pwd)/config

source ${wkdir}/function

#####################################################################CLS#

rm -rf ${wbapp}/etc/*
rm -rf ${wbapp}/var/*/*
rm -rf ${htdoc}/*/{log,temp}

rm -rf ${wbapp}/share/{doc,info,man}
rm -rf ${wblib}/share/{doc,info,man}

find /srv -name ".DS_Store" -type f -delete
find /srv -name "lost+found" -type d -delete

if [ "$OS_TYPE" = "Darwin" ]; then
    xattr -rd com.apple.quarantine /srv
fi

#####################################################################MIN#

if [ "$1" = "-min" ]; then

    rm -rf ${wbapp}/bin/phpize*
    rm -rf ${wbapp}/bin/phpdbg*
    rm -rf ${wbapp}/bin/php-config*
    rm -rf ${wbapp}/bin/mysql_config
    rm -rf ${wbapp}/include
    rm -rf ${wbapp}/lib/pkgconfig
    rm -rf ${wbapp}/share/aclocal
    rm -rf ${wbapp}/share/php*

    rm -rf ${wblib}/lib/cmake
    rm -rf ${wblib}/lib/gettext
    rm -rf ${wblib}/lib/libmcrypt
    rm -rf ${wblib}/lib/terminfo
    rm -rf ${wblib}/lib/pkgconfig
    rm -rf ${wblib}/lib/preloadable_*
    rm -rf ${wblib}/lib/xml2Conf.sh

    sf='curl\|openssl'
    for f in `ls ${wblib}/bin | grep -v ${sf}`; do
        rm -rf ${wblib}/bin/${f}
    done

    find /srv -name "*.a" -type f -delete
    find /srv -name "*.la" -type f -delete

    wk__strip ${wblib}/bin
    wk__strip ${wbapp}/bin
    wk__strip ${wbapp}/sbin

fi

#####################################################################PKG#

plat=$(uname -s)-$(getconf LONG_BIT)
dist=${wkdir}/Webox-${plat}bit$1.tgz

tar --exclude builder -czvf ${dist} /srv
