#!/bin/bash
#

if [ "$UID" != "0" ]; then
    echo "This script requires root privileges"
    exit 1
fi

#################################################################VAR#

[ -z ${wbdir} ] && wbdir=$(pwd)

[ -z ${webox} ] && webox=/srv/webox
[ -d ${webox} ] || mkdir -p ${webox}

[ -z ${wbget} ] && wbget=${wbdir}/wb_cache
[ -d ${wbget} ] || mkdir -p ${wbget}

[ -z ${wbsrc} ] && wbsrc=${wbdir}/wb_source
[ -d ${wbsrc} ] || mkdir -p ${wbsrc}

if [ -f /etc/lsb-release ]; then
    wbetc=${wbdir}/wb_profile/Ubuntu
else
    wbetc=${wbdir}/wb_profile/MacOS
fi

#################################################################RTM#

export PATH=${webox}/bin:${PATH}

export CPATH=${webox}/include
export LIBRARY_PATH=${webox}/lib

source ${wbetc}.rtm
