#!/bin/bash
#

if [ -f $(pwd)/wb_base ]; then
    source $(pwd)/wb_base
fi

if [ -z ${wbdir} ]; then
    echo "Please use './wk_publish' to run this script"
    exit 1
fi

source ${wbdir}/wb_function

#####################################################################MIN#

if [ "${1}" == "-min" ]; then

    mkdir -p /srv/webox/bin2
    mv /srv/webox/bin/{wkit,curl,openssl} /srv/webox/bin2

    for d in cmake gettext libmcrypt terminfo preloadable_*; do
        rm -rf /srv/webox/lib/${d}
    done

    rm -rf /srv/webox/{bin,etc,man,share}

    find /srv -name "*.a" -exec rm {} \;
    find /srv -name "*.la" -exec rm {} \;

    mv /srv/webox/bin2 /srv/webox/bin

    wb_strip /srv/webox/bin

    wb_strip /srv/mysql/bin
    wb_strip /srv/redis/bin

    wb_strip /srv/nginx/sbin

    if [ "$OSTYPE" == "Debian" ]; then
        wb_strip /srv/php5/bin
        wb_strip /srv/php5/sbin
        wb_strip /srv/php7/bin
        wb_strip /srv/php7/sbin
    fi

fi

#####################################################################CLS#

rm -rf /srv/*/var/run/*
rm -rf /srv/*/var/log/*
rm -rf /srv/*/var/tmp/*

rm -rf /srv/webox/var/ready/*

rm -rf /srv/mysql/var/data/*.cnf

if [ "$OSTYPE" == "MacOS" ]; then
    xattr -rd com.apple.quarantine /srv
fi

find /srv -type f -name "*.log" -exec rm {} \;
find /srv -type f -name "*.pid" -exec rm {} \;
find /srv -type f -name ".DS_Store" -exec rm {} \;
find /srv -type f -name "sess_*" -exec rm {} \;
find /srv -type d -name "lost+found" -exec rm {} \;

#####################################################################PKG#

plat=$(uname -s)-$(getconf LONG_BIT)
dist=${wbdir}/Webox-${plat}bit${1}.tgz

tar --exclude builder -czvf ${dist} /srv

