#!/bin/sh
#

export APP_USER=_www
export APP_GROUP=_www
export APP_DATA=${htdoc}

#####################################################################

app_prepare() {

    [ -d ${wbapp}/var/log/php5 ] || mkdir -p ${wbapp}/var/log/php5
    [ -d ${wbapp}/var/run/php5 ] || mkdir -p ${wbapp}/var/run/php5
    [ -d ${wbapp}/var/tmp/php5 ] || mkdir -p ${wbapp}/var/tmp/php5

    chown -R $APP_USER:$APP_USER ${wbapp}/var/*/php5

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
