#!/bin/sh
#

export APP_USER=_www
export APP_GROUP=_www

#####################################################################

app_prepare() {

    for dir in log run tmp; do
        [ -d ${wbapp}/var/${dir}/php5 ] ||
            mkdir -p ${wbapp}/var/${dir}/php5
    done

    if [ ! -e ${wbapp}/etc/php5 ]; then
        if [ -f /.dockerenv ]; then
            cp -a ${webox}/php5/etc ${wbapp}/etc/php5
        else
            ln -s ${webox}/php5/etc ${wbapp}/etc/php5
        fi
    fi

    chown -R $APP_USER:$APP_GROUP ${wbapp}/var/*/php5

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
