#!/bin/sh
#

export APP_USER=_mysql
export APP_GROUP=_mysql

#####################################################################

app_prepare() {

    local DIR

    for DIR in lib log run tmp; do
        [ -d ${wbapp}/var/$DIR/mysql ] ||
            mkdir -p ${wbapp}/var/$DIR/mysql
    done

    if [ ! -f ${wbapp}/var/log/mysql/error.log ]; then
        touch ${wbapp}/var/log/mysql/error.log
    fi

    chown -R $APP_USER:$APP_GROUP ${wbapp}/var/*/mysql

    if [ ! -f ${wbapp}/var/lib/mysql/ibdata1 ]; then
        ${wbapp}/sbin/mysqld --initialize-insecure --user=$APP_USER
    fi

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
