#!/bin/sh
#

export APP_NAME=xx
export APP_USER=daemon
export APP_GROUP=daemon
export APP_BIN_FILE=${webox}/bin/xx
export APP_PID_FILE=${webox}/var/run/xx.pid

#####################################################################
# 默认服务接口

do_start() {

    $APP_BIN_FILE

}

do_stop() {

    kill -TERM `cat $APP_PID_FILE`

}

do_reload() {

    kill -HUP `cat $APP_PID_FILE`

}

do_prepare() {

    app_prepare

}

#####################################################################
# 服务管理方法

app_start() {

    if app_isrun; then
        echo "$APP_NAME is already running"
        exit 1
    fi

    if [ ! -d /var/webox/$APP_NAME ]; then
        mkdir -p /var/webox/$APP_NAME
        echo "prepare $APP_NAME ..."
        do_prepare
    fi

    echo "start $APP_NAME ..."
    do_start

}

app_stop() {

    if ! app_isrun; then
        echo "$APP_NAME is not running"
        exit 1
    fi

    echo "stop $APP_NAME ..."
    do_stop

    while app_isrun; do sleep 1; done;

}

app_reload() {

    if ! app_isrun; then
        echo "$APP_NAME is not running"
        exit 1
    fi

    echo "reload $APP_NAME ..."
    do_reload

}

app_restart() {

    app_stop && sleep 3 && app_start

}

app_status() {

    app_isrun
    app_print "status:" "running" "stopped"

}

#####################################################################
# 服务检测方法

app_usage() {

    local DOES="start|stop|reload|restart|status"

    if ! echo "|$DOES|" | grep -q "|$1|"; then
        echo "Usage: wkit $APP_NAME {$DOES}"
        exit 1
    fi

}

app_isrun() {

    if [ ! -f $APP_PID_FILE ]; then
        return 1
    fi

    if ! kill -0 `cat $APP_PID_FILE` 2>/dev/null; then
        rm -f $APP_PID_FILE
        return 1
    fi

}

app_print() {

    local CODE=$?

    local RIGHT=${2:-done}
    local ERROR=${3:-failed}

    if [ $CODE -eq 0 ]; then
        echo "$1 $APP_NAME $RIGHT"
    else
        echo "$1 $APP_NAME $ERROR"
    fi

    exit $CODE

}

#####################################################################
# 服务设置方法

app_prepare() {

    local EDIR SDIR

    EDIR=${webox}/etc/$APP_NAME
    [ -d $EDIR ] && chown -R 0:0 $EDIR

    for SDIR in ${@:-lib log run tmp}; do
        mkdir -p ${webox}/var/$SDIR/$APP_NAME
        app_userlet ${webox}/var/$SDIR/$APP_NAME
    done

}

app_userlet() {

    chown -R $APP_USER:$APP_GROUP $1

    if [ -f $1/ibdata1 ]; then
        find $1 \( ! -perm 0640 -type f \) -exec chmod 0640 {} \;
        find $1 \( ! -perm 0750 -type d \) -exec chmod 0750 {} \;
    else
        find $1 \( ! -perm 0644 -type f \) -exec chmod 0644 {} \;
        find $1 \( ! -perm 0755 -type d \) -exec chmod 0755 {} \;
    fi

}
