#!/bin/sh
#

export APP_USER=mysql
export APP_GROUP=mysql

export APP_ROOT=/srv/mysql

#####################################################################

app_prepare() {

    if ! grep $APP_GROUP /etc/group >/dev/null; then
        groupadd $APP_GROUP -g 77
    fi

    if ! grep $APP_USER /etc/passwd >/dev/null; then
        useradd $APP_USER -u 77 -g 77
        usermod $APP_USER -d $APP_ROOT -s /usr/sbin/nologin
    fi

    [ -d $APP_ROOT/var/log ] || mkdir -p $APP_ROOT/var/log
    [ -d $APP_ROOT/var/tmp ] || mkdir -p $APP_ROOT/var/tmp
    [ -d $APP_ROOT/var/run ] || mkdir -p $APP_ROOT/var/run

    if [ ! -f $APP_ROOT/var/data/ibdata1 ]; then
        $APP_ROOT/bin/mysqld --initialize-insecure \
            --basedir=$APP_ROOT --datadir=$APP_ROOT/var/data
    fi

    chown -R $APP_USER:$APP_USER $APP_ROOT/var

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
