#!/bin/bash
#

if [ ! -e $whome/lib/gcc ]; then
    brew_install gcc
fi

if [ ! -e $whome/cell/glibc ]; then
    brew_install glibc
fi

if [ ! -e $whome/cell/pcre ]; then
    brew_install pcre
fi

if [ ! -e $whome/include/libxml ]; then
    brew_install libxml2
fi

if [ ! -e $whome/cell/imagemagick@6 ]; then
    sed -i "/keg_only/d" `brew --repository homebrew/core`/Formula/imagemagick@6.rb
fi
