#!/bin/bash
#

if [ ! -e $whome/lib/gcc ]; then
    brew_install gcc
fi

if [ ! -e $whome/cell/glibc ]; then
    brew_install glibc
fi

if [ ! -e $whome/cell/libpcre ]; then
    brew_install libpcre
fi

if [ ! -e $whome/include/libxml ]; then
    brew_install libxml2
fi
