#!/bin/bash
#

if [ -z "$whome" ]; then
    export wbase=`pwd`
    export whome=$wbase/webox
fi

if ! echo $PATH | grep -q $whome; then
    export PATH=$whome/bin:$whome/sbin:$PATH
fi

if [ -z "$wplat" ]; then
    export wplat=$([ `uname` = "Darwin" ] && echo macos || echo linux)
fi

##############################################HELPERS################

source $wbase/Declare/perform/global
source $wbase/Declare/perform/homebrew
source $wbase/Declare/perform/os_$wplat

source $wbase/Declare/perform/make_package
source $wbase/Declare/perform/make_profile

env_initialize() {
    deps_install && homebrew_init
}
