#!/bin/bash
#

export webox=/opt/webox

export wbase=$(cd `dirname $0`; pwd)

export wplat=$([ `uname` = "Darwin" ] && echo macos || echo linux)

##############################################HELPERS################

if ! echo $PATH | grep -q $webox; then
    export PATH=$webox/bin:$webox/sbin:$PATH
fi

load_modules() {

    source $wbase/Declare/module/global
    source $wbase/Declare/module/homebrew
    source $wbase/Declare/module/os_$wplat

    source $wbase/Declare/module/make_package
    source $wbase/Declare/module/make_profile

}

init_toolchain() {

    load_modules

    deps_install && homebrew_init

    source $wbase/Declare/preload

}
